#!/bin/bash

alias ll='ls -halo'
alias lt='ls -halot'
alias lr='ls -halotr'
alias lsd='ls -A | grep / | cut -f1 -d/'
alias lsd='ls -A | grep -v /'
alias 0='clear'
alias millis='date +%s%3N'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

alias npi='npm i --no-optional'
alias npu='npm u'
alias nps='npm start'
alias npt='npm test'

# git aliases
alias gg='git status -s'
alias gs='git status'
alias gpul='git pull --prune'
alias gpsh='git push origin HEAD'
alias gc='git checkout'
alias gcd='git checkout develop'
alias gcm='git checkout master'
alias gb='git branch'
alias gba='git branch -a'
alias gt='git tag'
alias gl='git log --oneline'
alias gd='git diff'
alias gds='git diff --staged'
alias stage='git add .'
alias unstage='git reset HEAD .'
alias discard='git checkout -- .'
alias dry-clean='git clean -ndf'
alias clean='git clean -df'
alias stash='git stash save -u'
